### ISSUE TITLE
Make status for policy violations configurable

### ISSUE THREAD

**Issue by gubraun** [blackducksoftware/github-action#4]
Great job on this project, works great!

I'd like to truly fail a workflow in case of policy violations. Currently, only a warning is annotated, by I don't have a way to fail the workflow, other than hacking (i.e. append something to the "args" like "|| /bin/false" or alike. Would be great if this was configurable in some way.

**Comment by gautambaghel** [comment]
Fixed in release 2.0.1 to configure break policy use 

https://blackducksoftware.github.io/synopsys-detect/latest/properties/Configuration/project/#fail-on-policy-violation-severities


so for example it should look something like,

```name: Synopsys Detect
      uses: blackducksoftware/github-action@2.0.1
      with:
        args: --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.tools="DETECTOR" --detect.policy.check.fail.on.severities=ALL
```
<img width="1151" alt="Screen Shot 2020-03-16 at 3 38 27 PM" src="https://user-images.githubusercontent.com/22324290/76793908-5a8d7300-679c-11ea-9da0-4be5f5f1242f.png">
